// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ClusterProgressInfo cluster progress info
//
// swagger:model cluster-progress-info
type ClusterProgressInfo struct {

	// finalizing stage percentage
	FinalizingStagePercentage int64 `json:"finalizing_stage_percentage,omitempty"`

	// installing stage percentage
	InstallingStagePercentage int64 `json:"installing_stage_percentage,omitempty"`

	// preparing for installation stage percentage
	PreparingForInstallationStagePercentage int64 `json:"preparing_for_installation_stage_percentage,omitempty"`

	// total percentage
	// Required: true
	TotalPercentage *int64 `json:"total_percentage"`
}

// Validate validates this cluster progress info
func (m *ClusterProgressInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTotalPercentage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterProgressInfo) validateTotalPercentage(formats strfmt.Registry) error {

	if err := validate.Required("total_percentage", "body", m.TotalPercentage); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClusterProgressInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterProgressInfo) UnmarshalBinary(b []byte) error {
	var res ClusterProgressInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
